# Generated by Django 3.2.5 on 2021-08-07 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 7, 11, 9, 1, 379298, tzinfo=utc)),
        ),
    ]
