# Generated by Django 3.2.5 on 2021-08-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category.png', null=True, upload_to='category/'),
        ),
    ]
