# Generated by Django 3.2.5 on 2021-08-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Cooking', 'Cooking'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered')], default='Cooking', max_length=20, null=True),
        ),
    ]
