# Generated by Django 3.2.5 on 2021-08-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorderitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
