# Generated by Django 3.2.5 on 2021-08-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_tableorderitem_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableorder',
            options={},
        ),
    ]
